### ISSUE TITLE
facing issue in main.py

### ISSUE THREAD

**Issue by parimalbera7551** [cmavro/GNN-RAG#11]
when i run main.py facing this issue
Traceback (most recent call last):
  File "/home/sysadm/Documents/GNN-RAG-main/gnn/models/ReaRev/main.py", line 50, in <module>
    main()
  File "/home/sysadm/Documents/GNN-RAG-main/gnn/models/ReaRev/main.py", line 42, in main
    trainer.train(0, args.num_epoch - 1)
  File "/home/sysadm/Documents/GNN-RAG-main/gnn/models/ReaRev/train_model.py", line 131, in train
    loss, extras, h1_list_all, f1_list_all = self.train_epoch()
  File "/home/sysadm/Documents/GNN-RAG-main/gnn/models/ReaRev/train_model.py", line 222, in train_epoch
    loss, _, _, tp_list = self.model(batch, training=True)
  File "/home/sysadm/miniconda3/envs/santu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sysadm/Documents/GNN-RAG-main/gnn/models/ReaRev/rearev.py", line 160, in forward
    self.init_reason(curr_dist=current_dist, local_entity=local_entity,
  File "/home/sysadm/Documents/GNN-RAG-main/gnn/models/ReaRev/rearev.py", line 119, in init_reason
    rel_features, rel_features_inv = self.get_rel_feature()
  File "/home/sysadm/Documents/GNN-RAG-main/gnn/models/ReaRev/rearev.py", line 91, in get_rel_feature
    rel_features = self.instruction.question_emb(self.rel_features)
  File "/home/sysadm/miniconda3/envs/santu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LSTMInstruction' object has no attribute 'question_emb'

**Comment by cmavro** [comment]
Please try to use `--lm sbert` argument.
